version: "3"

tasks:
  tf_init:
    description: Init infrastructure.
    usage: "task tf_init"
    cmds:
      - terraform -chdir=_infrastructure/terraform init -reconfigure -backend-config="key=checkers.tfstate"

  tf_apply:
    description: Apply infrastructure
    usage: "task tf_apply "
    cmds:
      - terraform -chdir=_infrastructure/terraform apply

  tf_destroy:
    description: Destroy an infrastructure
    usage: "task tf_destroy"
    cmds:
      - terraform -chdir=_infrastructure/terraform destroy

  tf_console:
    description: Use the console
    usage: "task tf_console "
    cmds:
      - terraform -chdir=_infrastructure/terraform console

  tf_output_raw:
    description: Output an argument
    usage: "task tf_output_raw -- registry_url"
    cmds:
      - output=$(echo {{ .CLI_ARGS }} | cut -d " " -f1);
        echo $(terraform -chdir=_infrastructure/terraform output -raw ${output})

  tf_output:
    description: Output all of the outputs from the state
    usage: "task tf_output"
    cmds:
      - echo $(terraform -chdir=_infrastructure/terraform output)

  ssh:
    description: SSH into an EC2 instance
    usage: "task ssk_ec2 -- registry"
    cmds:
      - ec2_public_ip=$(terraform -chdir=_infrastructure/terraform/ output -raw ec2_public_ip);
        ssh_private_key_path=$(terraform -chdir=_infrastructure/terraform output -raw ssh_private_key_path);
        ssh -i ${ssh_private_key_path} ubuntu@${ec2_public_ip}

  apb:
    description: Run an ansible playbook
    usage: "task ansible_pb -- deploy"
    cmds:
      - playbook=$(echo {{ .CLI_ARGS }} | cut -d " " -f1);
        ansible-playbook -i inventory.ini _infrastructure/ansible/playbooks/${playbook}.yml

  tf_import:
    cmds:
      - resource=$(echo {{ .CLI_ARGS }} | cut -d " " -f2);
        resource_id=$(echo {{ .CLI_ARGS }} | cut -d " " -f3);
        terraform -chdir=_infrastructure/terraform import ${resource} ${resource_id}
