version: "3"

tasks:
  tf_init:
    description: Init an infrastructure stack. Do not use on the organization stack.
    usage: "task tf_init -- staging registry"
    cmds:
      - terraform -chdir=_infrastructure/terraform init -reconfigure -backend-config="key=${stack}.tfstate"

  tf_apply:
    description: Apply an infrastructure stack
    usage: "task tf_apply -- staging registry"
    cmds:
      - terraform -chdir=_infrastructure/terraform apply

  tf_destroy:
    description: Destroy an infrastructure stack
    usage: "task tf_destroy -- staging registry"
    cmds:
      - terraform -chdir=_infrastructure/terraform destroy

  tf_console:
    description: Use the console for an infrastructure stack
    usage: "task tf_console -- staging registry"
    cmds:
      - terraform -chdir=_infrastructure/terraform console

  tf_output_raw:
    description: Output an argument from a state
    usage: "task tf_output_raw -- registry registry_url"
    cmds:
      - output=$(echo {{ .CLI_ARGS }} | cut -d " " -f2);
        echo $(terraform -chdir=_infrastructure/terraform output -raw ${output})

  tf_output:
    description: Output all of the outputs from the state
    usage: "task tf_output -- registry"
    cmds:
      - output=$(echo {{ .CLI_ARGS }} | cut -d " " -f2);
        echo $(terraform -chdir=_infrastructure/terraform output)

  ssh:
    description: SSH into an EC2 instance
    usage: "task ssk_ec2 -- registry"
    cmds:
      - ec2_public_ip=$(terraform -chdir=_infrastructure/terraform/stacks/web output -raw ec2_public_ip);
        ssh -i ./_infrastructure/terraform/stacks/web/github_id_rsa ubuntu@${ec2_public_ip}

  apb:
    description: Run an ansible playbook
    usage: "task ansible_pb -- deploy"
    cmds:
      - playbook=$(echo {{ .CLI_ARGS }} | cut -d " " -f1);
        ansible-playbook -i inventory.ini _infrastructure/ansible/playbooks/${playbook}.yml

  tf_import:
    cmds:
      - resource=$(echo {{ .CLI_ARGS }} | cut -d " " -f2);
        resource_id=$(echo {{ .CLI_ARGS }} | cut -d " " -f3);
        terraform -chdir=_infrastructure/terraform import ${resource} ${resource_id}
