---
- name: Deploy Portfolio Application
  hosts: portfolio
  become: yes
  vars:
    domain_name: "checkers-api.{{ lookup('env', 'TF_VAR_domain_name') }}.{{ lookup('env', 'TF_VAR_tld') }}"
    email: "{{ lookup('env', 'TF_VAR_email') }}"

  roles:
    - role: flask
    - role: nginx

  handlers:
    - name: Reload UFW
      ufw:
        state: reloaded
